# Dataset EDA

The purpose of this notebook is to test and explore the class: SleepinessDataset

In [ ]:
# Add the src directory to Python path
import sys
sys.path.append('../src')

In [ ]:
import pandas as pd

In [ ]:
# Import the dataset class
from data.sleepiness_dataset import SleepinessDataset

In [ ]:
dataset = SleepinessDataset()
df = dataset.load()

Loading SleepinessDataset with parameters:
  - Segment: 5
  - Variant: periods
  - Feature type: delta
  - KSS interpolation: linear
  - Data cleaning: True
Loading physiological data from: features_segm_5.csv
Loading questionnaire data from: Exp4_Database.csv
Merging physiological features with KSS labels...

Applying data cleaning...
Dropping 9 features with >50.0% missing values:
   1. HRV_SDANN2_Dr-Bl: 57.9% missing
   2. HRV_SDNNI2_Dr-Bl: 57.9% missing
   3. HRV_SDANN5_Dr-Bl: 100.0% missing
   4. HRV_SDNNI5_Dr-Bl: 100.0% missing
   5. HRV_ULF_Dr-Bl: 100.0% missing
   6. HRV_VLF_Dr-Bl: 100.0% missing
   7. RRV_VLF_Dr-Bl: 100.0% missing
   8. RRV_LFn_Dr-Bl: 100.0% missing
   9. RRV_HFn_Dr-Bl: 100.0% missing
Data cleaning: (599, 139) -> (599, 130)

Dataset loaded successfully: (599, 130)
Features: 123
Samples: 599
Subjects: 60

In [ ]:
df

,subject_id,label_sleep,first_scenario,label_time_exp,period,segment_id,kss,EDA_filtered_mean_Dr-Bl,EDA_filtered_min_Dr-Bl,EDA_filtered_max_Dr-Bl,...,SCR_Peaks_N_Dr-Bl,SCR_Peaks_Amplitude_Mean_Dr-Bl,RSA_P2T_Mean_Dr-Bl,RSA_P2T_Mean_log_Dr-Bl,RSA_P2T_SD_Dr-Bl,RSA_P2T_NoRSA_Dr-Bl,RSA_PorgesBohrer_Dr-Bl,RSA_Gates_Mean_Dr-Bl,RSA_Gates_Mean_log_Dr-Bl,RSA_Gates_SD_Dr-Bl
0,1,0,Rural,16,Rural,0,4.00,6.240796,5.929979,6.341950,...,16.0,0.157879,-0.003551,-0.116674,0.001146,0.0,0.400630,-0.231271,-0.029140,0.012048
1,1,0,Rural,16,Rural,1,3.75,4.933697,4.806328,4.407790,...,-1.0,0.012626,-0.003768,-0.124247,-0.000265,0.0,0.175800,-0.171799,-0.021565,0.015757
2,1,0,Rural,16,Rural,2,3.50,5.188408,5.132712,5.517033,...,-1.0,0.254859,-0.001096,-0.034572,0.007145,0.0,0.303468,-0.171153,-0.021484,0.015238
3,1,0,Rural,16,Rural,3,3.25,4.416023,4.516889,3.809360,...,-1.0,-0.075401,-0.002492,-0.080434,0.006244,0.0,0.167533,-0.118763,-0.014858,0.017757
4,1,0,Rural,16,Rural,4,3.00,3.858262,3.911289,3.446269,...,25.0,-0.125719,-0.001319,-0.041778,0.005092,0.0,0.210252,-0.136638,-0.017114,0.015136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,63,0,Rural,10,Urban,0,5.00,4.297119,5.765870,1.458715,...,4.0,-0.334532,0.057900,0.473816,0.059633,-3.0,0.403092,0.257815,0.029952,0.250294
595,63,0,Rural,10,Urban,1,5.00,3.877850,5.888398,0.597394,...,8.0,-0.375906,0.089367,0.660375,0.125910,0.0,1.054768,0.352011,0.040675,0.155602
596,63,0,Rural,10,Urban,2,5.00,3.138770,5.231840,-0.370577,...,15.0,-0.437024,0.059218,0.482372,0.091724,-2.0,0.764430,0.256710,0.029825,0.162742
597,63,0,Rural,10,Urban,3,5.00,2.857083,4.314966,-0.519343,...,1.0,-0.405648,0.021507,0.203057,0.042716,0.0,0.459075,0.133118,0.015577,0.139558
598,63,0,Rural,10,Urban,4,5.00,2.984107,5.359936,-1.032409,...,13.0,-0.444773,0.056754,0.466324,0.075927,-1.0,0.969632,0.285997,0.033172,0.229130

In [ ]:
# Pick random subject
subject_id = 23

In [ ]:
# 1. Original questionnaire data
quest_df = pd.read_csv('../.data/AdVitam/Exp4/Preprocessed/Questionnaire/Exp4_Database.csv')
subject_quest = quest_df[quest_df['participant_code'].str.startswith(f'{subject_id}_')]
print("1. Questionnaire data:")
subject_quest[['participant_code', 'order_scenario', 'KSS_B_1', 'KSS_1', 'KSS_B_2', 'KSS_2']]

1. Questionnaire data:

   participant_code  order_scenario  KSS_B_1  KSS_1  KSS_B_2  KSS_2
22          23_DU16               2        4      4        6      5

In [ ]:
# 2. Original physio data  
physio_df = pd.read_csv('../.data/AdVitam/Exp4/Preprocessed/Physio/periods/features_segm_5.csv')
subject_physio = physio_df[physio_df['subject_id'] == subject_id]
print("\n2. Physio data:")
subject_physio[['subject_id', 'period', 'segment_id', 'label_first_scenario']]

2. Physio data:

     subject_id period  segment_id label_first_scenario
219          23  Urban           0                Urban
220          23  Urban           1                Urban
221          23  Urban           2                Urban
222          23  Urban           3                Urban
223          23  Urban           4                Urban
224          23  Rural           0                Urban
225          23  Rural           1                Urban
226          23  Rural           2                Urban
227          23  Rural           3                Urban
228          23  Rural           4                Urban

In [ ]:
subject_final = df[df['subject_id'] == subject_id]
print("\n3. Final merged data:")
subject_final[['subject_id', 'period', 'segment_id', 'first_scenario', 'kss']]

3. Final merged data:

     subject_id period  segment_id first_scenario   kss
219          23  Urban           0          Urban  4.00
220          23  Urban           1          Urban  4.00
221          23  Urban           2          Urban  4.00
222          23  Urban           3          Urban  4.00
223          23  Urban           4          Urban  4.00
224          23  Rural           0          Urban  6.00
225          23  Rural           1          Urban  5.75
226          23  Rural           2          Urban  5.50
227          23  Rural           3          Urban  5.25
228          23  Rural           4          Urban  5.00